#! /bin/bash

synclient tapButton1=1 &

#xsetroot -solid "#282828"

feh --bg-tile Pictures/wallpaper/tiles/cheap_diagonal_fabric.png

#dropbox start &

# statusbar loop
while true; do
    xsetroot -name "$( cat /sys/class/power_supply/BAT1/capacity )% | $( date +"%a %R")"
    sleep 1m
done &

exec dwm
