#! /bin/bash

xset fp+ $HOME/.fonts
xset fp rehash

. $HOME/.wp

sxhkd -c $HOME/.config/sxhkd/sxhkdrc.wmutils &

feh --bg-scale $wp &

homer &

szyslak &

focus_watcher.sh &

synclient tapButton1=1 &

exec xwait
