#! /bin/bash

sxhkd &

xsetroot -solid "#cccccc"

bspc monitor -d I II III IV V 

#
# Appearance
#

bspc config border_width            5
bspc config window_gap              20

bspc config normal_border_color     '#e8e8ea'
bspc config focused_border_color    '#cd2536'
bspc config presel_feedback_color   '#cd2536'

#
# Behaviour
#

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

#
# Rules
#

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a URxvt state=pseudo_tiled

szyslak &
