#! /bin/bash

sxhkd -c ~/.config/sxhkd/sxhkdrc.bspwm &

. grabcolours.sh
. $HOME/.wp

feh --bg-scale $wp

synclient tapButton1=1

bspc monitor -d I II III IV  

#
# Appearance
#

bspc config border_width            4
bspc config window_gap              20


bspc config normal_border_color     "#$bg"
bspc config focused_border_color    "#$fg"
bspc config presel_feedback_color   "#$bg"

#
# Behaviour
#

bspc config split_ratio             0.5
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true

#
# Rules
#

bspc rule -a mplayer2 state=floating
bspc rule -a URxvt state=pseudo_tiled
bspc rule -a feh state=pseudo_tiled
