#! /bin/sh

cp .config/sxhkd/sxhkdrc.bspwm .config/sxhkd/sxhkdrc
sxhkd &

bspc monitor -d I II III IV V

bspc config border_width        4
bspc config window_gap          80
#bspc config top_padding         28 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config remove_disabled_monitor true

bspc config focus_follows_pointer true

bspc rule -a Screenkey manage=off
#bspc rule -a URxvt state=floating
bspc rule -a Xarchiver state=floating

synclient TapButton1=1

bspc config normal_border_color     "#2b2b2b"
bspc config focused_border_color    "#e6e1dc"
nm-applet & 

#compton --config .config/compton/compton.conf -b &

feh --bg-scale /home/spinks/Pictures/wallpaper/mono-morecambe.jpg
jbar "#e6e1dc" &

#shufflescheme &
